model :
  channel_dim : 1
  hidden_dim : 64
  latent_dim : 128

train :
  batch_size : 64
  nb_epochs : 50
  g_learning_rate : 0.0003
  d_learning_rate : 0.00015

dataset :
  name : "mnist"
  subset_size : null